version: "3"
services:
  urban-eats-client:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - "80:5173"
    command: npm run serve
    networks:
      - urban-eats
