version: "3"
services:
  urban-eats-client:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
    networks:
      - urban-eats

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - urban-eats-client
    networks:
      - urban-eats

networks:
  urban-eats:
    driver: bridge
