name: CI checks
on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - "dev"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install

      - name: Fetch all branches
        run: git fetch --all

      - name: Determine changed files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_BRANCH="${{ github.event.pull_request.base.sha }}"
            HEAD_BRANCH="${{ github.event.pull_request.head.sha }}"
            CHANGED_FILES=$(git diff --name-only "$BASE_BRANCH" "$HEAD_BRANCH" | grep -E '\.jsx?$')
          else
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E '\.jsx?$')
          fi

          # Trim "urban-eats-client/" prefix from file paths
          CHANGED_FILES=$(echo "$CHANGED_FILES" | sed 's|^urban-eats-client/||')

          # Convert newline separated list of files to space-separated list
          CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ' ')

          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
        shell: bash

      - name: Verify file existence
        run: |
          echo "Verifying file existence..."
          pwd
          echo "$CHANGED_FILES" | while read -r file; do
            if [ -f "$file" ]; then
              echo "$file exists"
            else
              echo "$file does not exist"
            fi
          done
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}

      - name: Run lint on changed files
        run: |
          pwd
          if [ -n "$CHANGED_FILES" ]; then
            echo "$CHANGED_FILES" | tr ' ' '\n' > changed_files.txt
            echo "Linting the following files:"
            cat changed_files.txt
            # Initialize exit code
            LINT_EXIT_CODE=0
            while IFS= read -r file; do
              if [ -f "$file" ]; then
                echo "Linting $file"
                ./node_modules/.bin/eslint "$file" --report-unused-disable-directives --max-warnings 0 || LINT_EXIT_CODE=$?
              else
                echo "$file does not exist"
              fi
            done < changed_files.txt
            # Exit with the combined exit code
            exit $LINT_EXIT_CODE
          else
            echo "No JavaScript/JSX files were changed."
          fi
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          npm install
          npm test

  merge_to_dev:
    runs-on: ubuntu-latest
    needs: unit_test
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git credentials
        run: |
          git config --global user.email hazrat17016@gmail.com
          git config --global user.name "Hazrat16"
          echo "GitCred=$(git config --list)"

      - name: Debug information
        run: |
          echo "Branch to merge: ${{ env.BRANCH_NAME }}"
          git branch -a
          git log --oneline --decorate --graph --all

      - name: Create and Checkout dev branch (if not exists)
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/dev; then
            git checkout dev
          else
            git checkout -b dev origin/dev
          fi

      - name: Fetch feature branch
        run: |
          git fetch origin ${{ env.BRANCH_NAME }}:refs/remotes/origin/${{ env.BRANCH_NAME }}
          git branch -r

      - name: Merge feature branch into dev
        run: |
          git checkout dev
          echo "Merging branch ${{ env.BRANCH_NAME }} into dev"
          git merge --no-ff ${{ env.BRANCH_NAME }} || {
            echo "Merge failed. Resolve conflicts manually.";
            exit 1;
          }

      - name: Push changes to dev
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push origin dev
