name: CI checks
on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - "dev"

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          npm install
          npm test

  merge_to_dev:
    runs-on: ubuntu-latest
    needs: unit_test
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git credentials
        run: |
          git config --global user.email hazrat17016@gmail.com
          git config --global user.name "Hazrat16"
          echo "GitCred=$(git config --list)"

      - name: Get branch name
        id: get_branch
        run: |
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Debug information
        run: |
          echo "Branch to merge: ${{ env.BRANCH_NAME }}"
          git branch -a
          git log --oneline --decorate --graph --all

      - name: Checkout dev branch
        run: |
          git fetch origin dev
          git checkout dev

      - name: Fetch feature branch
        run: |
          git fetch origin ${{ env.BRANCH_NAME }}

      - name: Merge feature branch into dev
        run: |
          git merge --no-ff ${{ env.BRANCH_NAME }} || {
            echo "Merge failed. Resolve conflicts manually.";
            exit 1;
          }

      - name: Push changes to dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin dev
